/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminMergesRouteImport } from './routes/admin.merges'
import { Route as AdminPlacesRouteImport } from './routes/admin.places'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminScoutRouteImport } from './routes/admin.scout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMergesRoute = AdminMergesRouteImport.update({
  id: '/merges',
  path: '/merges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScoutRoute = AdminScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/merges': typeof AdminMergesRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scout': typeof AdminScoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/merges': typeof AdminMergesRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scout': typeof AdminScoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/merges': typeof AdminMergesRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scout': typeof AdminScoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/merges'
    | '/admin/places'
    | '/admin/review'
    | '/admin/scout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/merges'
    | '/admin/places'
    | '/admin/review'
    | '/admin/scout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/merges'
    | '/admin/places'
    | '/admin/review'
    | '/admin/scout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merges': {
      id: '/admin/merges'
      path: '/merges'
      fullPath: '/admin/merges'
      preLoaderRoute: typeof AdminMergesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scout': {
      id: '/admin/scout'
      path: '/scout'
      fullPath: '/admin/scout'
      preLoaderRoute: typeof AdminScoutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMergesRoute: typeof AdminMergesRoute
  AdminPlacesRoute: typeof AdminPlacesRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminScoutRoute: typeof AdminScoutRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMergesRoute: AdminMergesRoute,
  AdminPlacesRoute: AdminPlacesRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminScoutRoute: AdminScoutRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
